### PR TITLE
feat(secops): add dive package

### PR DESCRIPTION
**Pull request by this-is-tobi**
Add [dive](https://github.com/wagoodman/dive) package.

### CODE REVIEW

**Comment by fyhertz** [comment]
Thanks! Could you update the summary and description and I will be happy to merge.

**Comment by this-is-tobi** [comment]
I wrote more information in the description but the summary is taken from the Github repository description, should I rewrite it @fyhertz ?

**Comment by fyhertz** [comment]
Yes, could your remove the leading "A". The debian guidelines recommend not to start the summary by an article:

> The synopsis functions as a phrase describing the package, not a complete sentence, so sentential punctuation is inappropriate: it does not need extra capital letters or a final period (full stop). It should also omit any initial indefinite or definite article — "a", "an", or "the".

https://www.debian.org/doc/manuals/developers-reference/best-pkging-practices.en.html#bpp-pkg-synopsis

This repo breaks a looooot of debian packaging rules, but those are easy to follow so I prefer to try to stick to them.

So the summary should actually be: `tool for exploring each layer in a docker image`

**Comment by this-is-tobi** [comment]
Thanks @fyhertz for the merge and for this awesome project !

**Pull request merged**
