### PR TITLE
feat(dev): add kubebuilder package

### PR DESCRIPTION
**Pull request by this-is-tobi**
Add [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) package

### CODE REVIEW

**Comment by fyhertz** [comment]
Thanks!

Could you replace with script section by an install section:

```yaml
install:
  kubebuilder_linux_{{arch}};/usr/bin/kubebuilder
```

Happy to merge your PR once this is done!

**Comment by fyhertz** [comment]
Yes, everything in /usr/bin is made executable automatically

**Comment by fyhertz** [comment]
Btw the diff between /usr/bin/ and /usr/local/bin is explained here: https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#cite_note-11

**Comment by fyhertz** [comment]
@this-is-tobi  The separator needs to be ":" !

**Comment by this-is-tobi** [comment]
@fyhertz I fixed the `;` by a `:` 🌸

**Comment by fyhertz** [comment]
Exactly!

**Pull request merged**
